### ISSUE TITLE
There seems to be a lot of BUG!

### ISSUE THREAD

**Issue by TianQi-777** [mavischer/DRRL#1]
1. The configuration of exmpl_config.yml has `list_goal_lengths`,`list_num_distractors` and `list_distractor_lengths`, and the inputs of `Box-World environment` are `goal_length`,`num_distractor` and `distractor_length`([here](https://github.com/mavischer/Box-World/blob/48c0b6c81a10d911b3b74ca62fad66d638310add/gym-boxworld/gym_boxworld/envs/boxworld_env.py#L56)), it can be run by changing 
```
list_goal_lengths: [2,3]
list_num_distractors: [1,2]
list_distractor_lengths: [1,2]
```
to
```
goal_length: 2
num_distractor: 1
distractor_length: 1
```
2. However, another bug will appear.
```
Traceback (most recent call last):
  File "a2c.py", line 259, in <module>
    episodes = [w.start() for w in workers] #list comprehension automatically waits for workers to finish
  File "a2c.py", line 259, in <listcomp>
    episodes = [w.start() for w in workers] #list comprehension automatically waits for workers to finish
  File "a2c.py", line 101, in start
    p, _ = self.l_net(s)
  File "/home/tianqi/anaconda3/envs/py3_torch/lib/python3.7/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/tianqi/DRRL/attention_module.py", line 185, in forward
    c = F.relu(self.conv1(x))
  File "/home/tianqi/anaconda3/envs/py3_torch/lib/python3.7/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/tianqi/anaconda3/envs/py3_torch/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 343, in forward
    return self.conv2d_forward(input, self.weight)
  File "/home/tianqi/anaconda3/envs/py3_torch/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 340, in conv2d_forward
    self.padding, self.dilation, self.groups)
RuntimeError: Given groups=1, weight of size 12 3 2 2, expected input[1, 10, 4, 11] to have 3 channels, but got 10 channels instead
```
How to solve it？In addition, can you provide a gym version?(I test on gym 0.17)

**Comment by mavischer** [comment]
thanks a lot for the notification! check out the readme, it will help you a bit with your questions: the current script to perform the training is a2c_fast.py. it also explains how to install the entire environment. best regards and good luck!

**Comment by TianQi-777** [comment]
Thank you for your reply :) Could tell me the version of gym you tested (I test on gym 0.17)
